### ISSUE TITLE
Errors while testing in Apple Mojave

### ISSUE THREAD

**Issue by hajsf** [exonum/exonum#1259]
Upon running

```shell
cargo test --manifest-path exonum/Cargo.toml
```

I got the below errors:

```bash
failures:
    events::tests::test_network_big_message
    events::tests::test_network_handshake
    events::tests::test_network_max_message_len
    events::tests::test_network_multiple_connect
    events::tests::test_network_reconnect
    events::tests::test_send_first_not_connect
    storage::proof_list_index::tests::rocksdb_tests::test_same_merkle_root
    storage::proof_map_index::tests::rocksdb_tests::test_fuzz_delete_build_proofs
    storage::proof_map_index::tests::rocksdb_tests::test_fuzz_insert
    storage::proof_map_index::tests::rocksdb_tests::test_fuzz_insert_after_delete
    storage::proof_map_index::tests::rocksdb_tests::test_fuzz_insert_build_multiproofs
    storage::proof_map_index::tests::rocksdb_tests::test_fuzz_insert_build_proofs
    storage::proof_map_index::tests::rocksdb_tests::test_fuzz_insert_build_proofs_in_table_filled_with_hashes
    storage::proof_map_index::tests::rocksdb_tests::test_insert_reverse
    storage::proof_map_index::tests::rocksdb_tests::test_insert_same_key
    storage::proof_map_index::tests::rocksdb_tests::test_insert_simple
    storage::proof_map_index::tests::rocksdb_tests::test_insert_trivial
    storage::proof_map_index::tests::rocksdb_tests::test_iter
    storage::proof_map_index::tests::rocksdb_tests::test_map_methods
    storage::proof_map_index::tests::rocksdb_tests::test_remove_reverse
    storage::proof_map_index::tests::rocksdb_tests::test_remove_simple
    storage::proof_map_index::tests::rocksdb_tests::test_remove_trivial
    storage::proof_map_index::tests::rocksdb_tests::test_tree_with_hashed_key
    storage::sparse_list_index::tests::rocksdb_tests::test_list_index_iter
    storage::sparse_list_index::tests::rocksdb_tests::test_list_index_methods

test result: FAILED. 328 passed; 25 failed; 3 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

**Comment by vitvakatu** [comment]
Could you please provide the output of `git rev-parse HEAD` command? I can't reproduce such issue on my Mac OS Mojave

**Comment by hajsf** [comment]
@vitvakatu here what I got:
```bash
Hasans-Air:~ h_ajsf$ cd exonum
Hasans-Air:exonum h_ajsf$ git rev-parse HEAD
a0b8934faefc89d59d98a21d58dff52b567e92c6
```

**Comment by vitvakatu** [comment]
Thank you. What Rust compiler version are you using? Could you provide the output of `rustup show`?

**Comment by hajsf** [comment]
@vitvakatu  I'm at nightly rust
```bash
Hasans-Air:exonum h_ajsf$ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-armv7-unknown-linux-gnueabihf
stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

installed targets for active toolchain
--------------------------------------

aarch64-linux-android
arm-linux-androideabi
armv7-linux-androideabi
armv7-unknown-linux-gnueabihf
i686-linux-android
wasm32-unknown-unknown
x86_64-apple-darwin
x86_64-linux-android

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.33.0-nightly (daa53a52a 2019-01-17)
```

**Comment by vitvakatu** [comment]
Could you try stable 1.32?

**Comment by hajsf** [comment]
@vitvakatu  The number of failures had been reduced, I got the below:
```bash
.
   Compiling exonum-crypto v0.10.3 (/Users/h_ajsf/exonum/components/crypto)
warning: redundant linker flag specified for library `c++`
.
failures:
    events::tests::test_network_big_message
    events::tests::test_network_handshake
    events::tests::test_network_max_message_len
    events::tests::test_network_multiple_connect
    events::tests::test_network_reconnect
    events::tests::test_send_first_not_connect

test result: FAILED. 347 passed; 6 failed; 3 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
Hasans-Air:exonum h_ajsf$ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-armv7-unknown-linux-gnueabihf
stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-ios
aarch64-linux-android
arm-linux-androideabi
armv7-apple-ios
armv7-linux-androideabi
armv7-unknown-linux-gnueabihf
armv7s-apple-ios
i386-apple-ios
i686-linux-android
wasm32-unknown-emscripten
wasm32-unknown-unknown
x86_64-apple-darwin
x86_64-apple-ios
x86_64-linux-android

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.32.0 (9fda7c223 2019-01-16)
```

**Comment by vitvakatu** [comment]
Thanks, we will investigate

**Comment by hajsf** [comment]
@vitvakatu today I updated all the crates in all `Cargo.toml` files to the latest crate of each, and I'm getting now the below:
```bash
   Compiling exonum_rocksdb v0.7.4
error[E0407]: method `fill_bytes` is not a member of trait `Random`
  --> exonum/src/events/noise/wrappers/sodium_wrapper/resolver.rs:88:5
   |
88 | /     fn fill_bytes(&mut self, out: &mut [u8]) {
89 | |         thread_rng().fill_bytes(out);
90 | |     }
   | |_____^ not a member of trait `Random`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0407`.
error: Could not compile `exonum`.
warning: build failed, waiting for other jobs to finish...
error[E0407]: method `fill_bytes` is not a member of trait `Random`
  --> exonum/src/events/noise/wrappers/sodium_wrapper/resolver.rs:88:5
   |
88 | /     fn fill_bytes(&mut self, out: &mut [u8]) {
89 | |         thread_rng().fill_bytes(out);
90 | |     }
   | |_____^ not a member of trait `Random`

error[E0407]: method `fill_bytes` is not a member of trait `Random`
   --> exonum/src/events/noise/wrappers/sodium_wrapper/resolver.rs:284:9
    |
284 | /         fn fill_bytes(&mut self, out: &mut [u8]) {
285 | |             let bytes = vec![self.0; out.len()];
286 | |             self.0 += 1;
287 | |             out.copy_from_slice(bytes.as_slice());
288 | |         }
    | |_________^ not a member of trait `Random`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0407`.
error: Could not compile `exonum`.

To learn more, run the command again with --verbose.
```

**Comment by vitvakatu** [comment]
@hajsf well, you don't need to update any of the packages inside our `Cargo.toml`, because such changes need some code modification (and that's why you have compile issues now).

**Comment by hajsf** [comment]
@vitvakatu understood, I thought this may solve the original issue :), but it complicated it, so we are back to square one.

**Comment by hajsf** [comment]
@vitvakatu / @ivan-ochc  hope you got chance to investigate this!

**Comment by aleksuss** [comment]
@hajsf I couldn't re-produce on my machine. Could you please provide steps you followed?

**Comment by ivan-ochc** [comment]
@hajsf, try to run tests with argument `--test-threads=1 ` or increase `ulimit`.

**Comment by hajsf** [comment]
I removed everything related to rust and exonum, repeated the steps, and it looks fine now, got some `ERROR` but 0 fail

**Comment by hajsf** [comment]
I removed both `rust` and `exonum`, re-installed every thing, initially was ok, with n fail, just run it again now, and got the below:
```bash
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5
test events::tests::test_network_big_message ... FAILED
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5
test events::tests::test_network_handshake ... FAILED
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5
test events::tests::test_network_max_message_len ... FAILED
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5
test events::tests::test_network_multiple_connect ... FAILED
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5
test events::tests::test_network_reconnect ... FAILED
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5
test events::tests::test_send_first_not_connect ... FAILED
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5

failures:
    events::tests::test_network_big_message
    events::tests::test_network_handshake
    events::tests::test_network_max_message_len
    events::tests::test_network_multiple_connect
    events::tests::test_network_reconnect
    events::tests::test_send_first_not_connect

test result: FAILED. 347 passed; 6 failed; 3 ignored; 0 measured; 0 filtered out
```

**Comment by vitvakatu** [comment]
@hajsf this looks like an issue with your `ulimit` setting. What is the output of `ulimit -n`? On my machine a have about 7000+

**Comment by hajsf** [comment]
@vitvakatu 
```bash
Hasans-Air:~ h_ajsf$ ulimit -n
256
```

What is this ulimit, and how to increase it?

**Comment by ivan-ochc** [comment]
@hajsf, these tests have passed without any problem. Could you please check this issue again? 
JFYI: ulimit on my machine:
```
ulimit -n
524288
```
