### ISSUE TITLE
Launcher fails to get proto sources

### ISSUE THREAD

**Issue by integrer** [exonum/exonum#1793]
On start launchers request for proto sources are rejected with code 400 without any message. Then it fails to parse response text as json (because it`s just empty).
<details>
<summary>Log output</summary>

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/exonum_launcher/__main__.py", line 6, in <module>
    run_cli()
  File "/usr/local/lib/python3.6/dist-packages/exonum_launcher/cli.py", line 46, in run_cli
    launcher_main(args)
  File "/usr/local/lib/python3.6/dist-packages/exonum_launcher/main.py", line 85, in main
    run_launcher(config)
  File "/usr/local/lib/python3.6/dist-packages/exonum_launcher/main.py", line 22, in run_launcher
    with Launcher(config) as launcher:
  File "/usr/local/lib/python3.6/dist-packages/exonum_launcher/launcher.py", line 75, in __enter__
    self.initialize()
  File "/usr/local/lib/python3.6/dist-packages/exonum_launcher/launcher.py", line 91, in initialize
    self._supervisor.initialize()
  File "/usr/local/lib/python3.6/dist-packages/exonum_launcher/supervisor.py", line 42, in initialize
    self._loader.load_main_proto_files()
  File "/usr/local/lib/python3.6/dist-packages/exonum_client/protobuf_loader.py", line 210, in load_main_proto_files
    proto_contents = self.client.get_main_proto_sources()
  File "/usr/local/lib/python3.6/dist-packages/exonum_client/client.py", line 532, in get_main_proto_sources
    return self._get_proto_sources()
  File "/usr/local/lib/python3.6/dist-packages/exonum_client/client.py", line 519, in _get_proto_sources
    json.dumps(response.json(), indent=2),
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
</details>

**Comment by vitvakatu** [comment]
Hello, thank you for creating an issue.

What version of launcher do you use with what version of Exonum?
To look for the former, you can use `pip3 freeze` command  - it will output all of your locally installed python packages and their versions.

My guess is that you're using `exonum-launcher` from `PyPI`, which isn't updated to the latest Exonum.

**Comment by integrer** [comment]
Hello. I used version 0.1.3 (installed by default).

**Comment by vitvakatu** [comment]
You should use a version from github repository:
```bash
git clone https://github.com/exonum/exonum-launcher
cd exonum-launcher
pip3 install -r requirements.txt
pip3 install -e .
```

**Comment by integrer** [comment]
Thank you! I can see that it solves problem.

**Comment by integrer** [comment]
But instead I get following error:
<details>
<summary>Log output</summary>

```
Deploying of crypto-election service is in progress...
Traceback (most recent call last):
  File "/usr/src/exonum-launcher/exonum_launcher/instances/default_spec_loader.py", line 30, in serialize_config
    instance.artifact.name, instance.artifact.version, "service"
Artifact exonum-time -> deploy status: succeed
Artifact crypto-election-node -> deploy status: succeed
  File "/usr/src/exonum-launcher/src/exonum-python-client/exonum_client/module_manager.py", line 36, in import_service_module
    module = importlib.import_module("exonum_modules.{}.{}_pb2".format(artifact_module_name, module_name))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'exonum_modules.crypto_election_node_0_2_0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/exonum-launcher/exonum_launcher/instances/default_spec_loader.py", line 38, in serialize_config
    instance.artifact.name, instance.artifact.version, "service"
  File "/usr/src/exonum-launcher/src/exonum-python-client/exonum_client/module_manager.py", line 36, in import_service_module
    module = importlib.import_module("exonum_modules.{}.{}_pb2".format(artifact_module_name, module_name))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'exonum_modules.crypto_election_node_0_2_0.service_pb2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/exonum-launcher/exonum_launcher/__main__.py", line 6, in <module>
    run_cli()
  File "/usr/src/exonum-launcher/exonum_launcher/cli.py", line 46, in run_cli
    launcher_main(args)
  File "/usr/src/exonum-launcher/exonum_launcher/main.py", line 97, in main
    run_launcher(config)
  File "/usr/src/exonum-launcher/exonum_launcher/main.py", line 37, in run_launcher
    launcher.start_all()
  File "/usr/src/exonum-launcher/exonum_launcher/launcher.py", line 142, in start_all
    self.config.consensus, self.config.instances, config_loaders, self.config.actual_from
  File "/usr/src/exonum-launcher/exonum_launcher/supervisor.py", line 161, in create_config_change_request
    self._build_start_service_change(instance, config_loader, config_change)
  File "/usr/src/exonum-launcher/exonum_launcher/supervisor.py", line 242, in _build_start_service_change
    start_service.config = config_loader.load_spec(self._loader, instance)
  File "/usr/src/exonum-launcher/exonum_launcher/instances/default_spec_loader.py", line 23, in load_spec
    return self.serialize_config(loader, instance, instance.config)
  File "/usr/src/exonum-launcher/exonum_launcher/instances/default_spec_loader.py", line 53, in serialize_config
    f"Couldn't get a proto description for artifact: {artifact_name}, error: {error}"
exonum_launcher.instances.instance_spec_loader.InstanceSpecLoadError: Couldn't get a proto description for artifact: crypto-election-node, error: No module named 'exonum_modules.crypto_election_node_0_2_0.service_pb2'
```

</details>
I guess it could be rust application misconfigured.

**Comment by integrer** [comment]
By the way, timestamping service fails to deploy too.
<details>
<summary>Log output</summary>

```
new node with ports: 8000 (public) and 8004 (private)
new node with ports: 8001 (public) and 8005 (private)
new node with ports: 8002 (public) and 8006 (private)
new node with ports: 8003 (public) and 8007 (private)
Deploying of timestamping service is in progress...
Artifact exonum-time -> deploy status: succeed
Artifact exonum-timestamping -> deploy status: failed
Unsuccessfully attempted to retrieve Protobuf sources.
Status code: 404,
body:
b'{"title":"Artifact sources not found","detail":"Unable to find sources for artifact 0:exonum-timestamping:1.0.0-rc.1"}'
Traceback (most recent call last):
  File "/exonum-launcher/exonum_launcher/instances/default_spec_loader.py", line 30, in serialize_config
    instance.artifact.name, instance.artifact.version, "service"
  File "/exonum-launcher/src/exonum-python-client/exonum_client/module_manager.py", line 36, in import_service_module
    module = importlib.import_module("exonum_modules.{}.{}_pb2".format(artifact_module_name, module_name))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'exonum_modules.exonum_timestamping_1_0_0_rc_1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/exonum-launcher/exonum_launcher/instances/default_spec_loader.py", line 35, in serialize_config
    instance.artifact.runtime_id, instance.artifact.name, instance.artifact.version
  File "/exonum-launcher/src/exonum-python-client/exonum_client/protobuf_loader.py", line 230, in load_service_proto_files
    proto_contents = self.client.get_proto_sources_for_artifact(runtime_id, artifact_name, artifact_version)
  File "/exonum-launcher/src/exonum-python-client/exonum_client/protobuf_provider/provider.py", line 114, in get_proto_sources_for_artifact
    return provider.get_proto_sources_for_artifact(runtime_id, artifact_name, artifact_version)
  File "/exonum-launcher/src/exonum-python-client/exonum_client/protobuf_provider/exonum_api.py", line 61, in get_proto_sources_for_artifact
    return self._get_proto_sources(params)
  File "/exonum-launcher/src/exonum-python-client/exonum_client/protobuf_provider/exonum_api.py", line 36, in _get_proto_sources
    raise RuntimeError("Unsuccessfully attempted to retrieve Protobuf sources: {!r}".format(response.content))
RuntimeError: Unsuccessfully attempted to retrieve Protobuf sources: b'{"title":"Artifact sources not found","detail":"Unable to find sources for artifact 0:exonum-timestamping:1.0.0-rc.1"}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/exonum-launcher/exonum_launcher/__main__.py", line 6, in <module>
    run_cli()
  File "/exonum-launcher/exonum_launcher/cli.py", line 46, in run_cli
    launcher_main(args)
  File "/exonum-launcher/exonum_launcher/main.py", line 97, in main
    run_launcher(config)
  File "/exonum-launcher/exonum_launcher/main.py", line 37, in run_launcher
    launcher.start_all()
  File "/exonum-launcher/exonum_launcher/launcher.py", line 142, in start_all
    self.config.consensus, self.config.instances, config_loaders, self.config.actual_from
  File "/exonum-launcher/exonum_launcher/supervisor.py", line 161, in create_config_change_request
    self._build_start_service_change(instance, config_loader, config_change)
  File "/exonum-launcher/exonum_launcher/supervisor.py", line 242, in _build_start_service_change
    start_service.config = config_loader.load_spec(self._loader, instance)
  File "/exonum-launcher/exonum_launcher/instances/default_spec_loader.py", line 23, in load_spec
    return self.serialize_config(loader, instance, instance.config)
  File "/exonum-launcher/exonum_launcher/instances/default_spec_loader.py", line 53, in serialize_config
    f"Couldn't get a proto description for artifact: {artifact_name}, error: {error}"
exonum_launcher.instances.instance_spec_loader.InstanceSpecLoadError: Couldn't get a proto description for artifact: exonum-timestamping, error: Unsuccessfully attempted to retrieve Protobuf sources: b'{"title":"Artifact sources not found","detail":"Unable to find sources for artifact 0:exonum-timestamping:1.0.0-rc.1"}'

```
</details>

**Comment by integrer** [comment]
I just tried to launch timestamping service and got following exception
<details>
<summary>Log output</summary>

```
new node with ports: 8000 (public) and 8004 (private)
new node with ports: 8001 (public) and 8005 (private)
new node with ports: 8002 (public) and 8006 (private)
new node with ports: 8003 (public) and 8007 (private)
Deploying of timestamping service is in progress...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/exonum-launcher/exonum_launcher/__main__.py", line 6, in <module>
    run_cli()
  File "/exonum-launcher/exonum_launcher/cli.py", line 46, in run_cli
    launcher_main(args)
  File "/exonum-launcher/exonum_launcher/main.py", line 99, in main
    run_launcher(config)
  File "/exonum-launcher/exonum_launcher/main.py", line 27, in run_launcher
    launcher.wait_for_deploy()
  File "/exonum-launcher/exonum_launcher/launcher.py", line 129, in wait_for_deploy
    self._explorer.wait_for_txs(tx_hashes)
  File "/exonum-launcher/exonum_launcher/explorer.py", line 87, in wait_for_txs
    self.wait_for_tx(tx_hash)
  File "/exonum-launcher/exonum_launcher/explorer.py", line 69, in wait_for_tx
    raise ExecutionFailError(f"Transaction execution failed: {status}")
exonum_launcher.explorer.ExecutionFailError: Transaction execution failed: {'type': 'service_error', 'description': 'Artifact `0:exonum-time:1.0.0-rc.2` is already deployed', 'code': 16, 'runtime_id': 0, 'call_site': {'instance_id': 0, 'call_type': 'method', 'method_id': 0}}

```
</details>

**Comment by integrer** [comment]
And cryptocyrrency advanced service fails to launch too.
<details>
<summary>Log output</summary>

```
new node with ports: 8000 (public) and 8004 (private)
new node with ports: 8001 (public) and 8005 (private)
new node with ports: 8002 (public) and 8006 (private)
new node with ports: 8003 (public) and 8007 (private)
Deploying of cryptocurrency-advanced service is in progress...
Artifact exonum-cryptocurrency-advanced -> deploy status: failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/exonum-launcher/exonum_launcher/__main__.py", line 6, in <module>
    run_cli()
  File "/exonum-launcher/exonum_launcher/cli.py", line 46, in run_cli
    launcher_main(args)
  File "/exonum-launcher/exonum_launcher/main.py", line 99, in main
    run_launcher(config)
  File "/exonum-launcher/exonum_launcher/main.py", line 38, in run_launcher
    launcher.wait_for_start()
  File "/exonum-launcher/exonum_launcher/launcher.py", line 152, in wait_for_start
    self._explorer.wait_for_txs(tx_hashes)
  File "/exonum-launcher/exonum_launcher/explorer.py", line 87, in wait_for_txs
    self.wait_for_tx(tx_hash)
  File "/exonum-launcher/exonum_launcher/explorer.py", line 69, in wait_for_tx
    raise ExecutionFailError(f"Transaction execution failed: {status}")
exonum_launcher.explorer.ExecutionFailError: Transaction execution failed: {'type': 'service_error', 'description': 'Discarded start of service `crypto` from the unknown artifact `exonum-cryptocurrency-advanced`.', 'code': 20, 'runtime_id': 0, 'call_site': {'instance_id': 0, 'call_type': 'method', 'method_id': 2}}

```
</details>

**Comment by aleksuss** [comment]
1. About the cryptocurrency advanced service. It deploys and starts in a genesis block now. So you don't need to use launcher to deploy and start it. You can communicate with the service immediately after the node start.

2. About the timestamping. We've changed a logic for rust services deployment. Every rust service deploys in the genesis block now. So you need to skip deploy stage and only start it to communicate with. To achieve this you should add `deploy = false` to the every section which describes an artifact. E.g. artifacts section for the timestamping service should look like this now:
```
artifacts:
  time:
    runtime: rust
    name: "exonum-time"
    version: "1.0.0-rc.2"
    deploy: false
  timestamping:
    runtime: rust
    name: "exonum-timestamping"
    version: "1.0.0-rc.2"
    deploy: false
```

**Comment by integrer** [comment]
Thank you for answer. Now all services starts as well.
