### ISSUE TITLE
error: failed to run custom build command for `exonum-proto v1.0.0`

### ISSUE THREAD

**Issue by jsoneaday** [exonum/exonum#2110]
I'm trying to build a project that uses exonum-crypto and jwt-compact. This is failing building on a docker image. Here's the logs with backtrace enabled.

#0 86.20 error: failed to run custom build command for `exonum-proto v1.0.0`
#0 86.20 
#0 86.20 Caused by:
#0 86.20   process didn't exit successfully: `/usr/src/syntaxmakersserver/target/debug/build/exonum-proto-4511d529eaae65e2/build-script-build` (exit status: 101)
#0 86.20   --- stdout
#0 86.20   cargo:protos=/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/exonum-proto-1.0.0/src/proto
#0 86.20 
#0 86.20   --- stderr
#0 86.20   thread 'main' panicked at 'protoc binary not found: cannot find binary path', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/protoc-2.28.0/src/lib.rs:209:17
#0 86.20   stack backtrace:
#0 86.20      0: rust_begin_unwind
#0 86.20                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
#0 86.20      1: core::panicking::panic_fmt
#0 86.20                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
#0 86.20      2: protoc::Protoc::from_env_path
#0 86.20                at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/protoc-2.28.0/src/lib.rs:209:17
#0 86.20      3: protoc_rust::Codegen::run
#0 86.20                at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/protoc-rust-2.28.0/src/lib.rs:173:21
#0 86.20      4: exonum_build::protobuf_generate
#0 86.20                at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/exonum-build-1.0.1/src/lib.rs:410:5
#0 86.20      5: exonum_build::ProtobufGenerator::generate
#0 86.20                at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/exonum-build-1.0.1/src/lib.rs:377:9
#0 86.20      6: build_script_build::main
#0 86.20                at ./build.rs:23:5
#0 86.20      7: core::ops::function::FnOnce::call_once
#0 86.20                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
#0 86.20   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
#0 86.20 warning: build failed, waiting for other jobs to finish...
#0 94.19 error: failed to compile `syntaxmakers-server v0.1.0 (/usr/src/syntaxmakersserver)`, intermediate artifacts can be found at `/usr/src/syntaxmakersserver/target`
------
failed to solve: executor failed running [/bin/sh -c CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true RUST_BACKTRACE=1 cargo install --debug --path .]: exit code: 101

**Comment by jsoneaday** [comment]
Was able to get passed this by installing protoc on my docker image, but now getting error about libsodium?

#0 199.1   ============================================================================
#0 199.1   Testsuite summary for libsodium 1.0.17
#0 199.1   ============================================================================
#0 199.1   # TOTAL: 75
#0 199.1   # PASS:  74
#0 199.1   # SKIP:  0
#0 199.1   # XFAIL: 0
#0 199.1   # FAIL:  1
#0 199.1   # XPASS: 0
#0 199.1   # ERROR: 0
#0 199.1   ============================================================================
#0 199.1   See test/default/test-suite.log
#0 199.1   Please report to https://github.com/jedisct1/libsodium/issues
#0 199.1   ============================================================================
#0 243.0   make[4]: Leaving directory '/usr/src/syntaxmakersserver/target/debug/build/exonum_libsodium-sys-0f0c3a9b3a75c0c1/out/source/libsodium-1.0.17/test/default'
#0 243.0   make[3]: Leaving directory '/usr/src/syntaxmakersserver/target/debug/build/exonum_libsodium-sys-0f0c3a9b3a75c0c1/out/source/libsodium-1.0.17/test/default'
#0 243.0   make[2]: Leaving directory '/usr/src/syntaxmakersserver/target/debug/build/exonum_libsodium-sys-0f0c3a9b3a75c0c1/out/source/libsodium-1.0.17/test/default'
#0 243.0   make[1]: Leaving directory '/usr/src/syntaxmakersserver/target/debug/build/exonum_libsodium-sys-0f0c3a9b3a75c0c1/out/source/libsodium-1.0.17/test'
#0 243.0 
#0 243.0   libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
#0 243.0   ar: `u' modifier ignored since `D' is the default (see `U')
#0 243.0   libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
#0 243.0   ar: `u' modifier ignored since `D' is the default (see `U')
#0 243.0   libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
#0 243.0   ar: `u' modifier ignored since `D' is the default (see `U')
#0 243.0   libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
#0 243.0   ar: `u' modifier ignored since `D' is the default (see `U')
#0 243.0   libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
#0 243.0   ar: `u' modifier ignored since `D' is the default (see `U')
#0 243.0   libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
#0 243.0   ar: `u' modifier ignored since `D' is the default (see `U')
#0 243.0   libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
#0 243.0   ar: `u' modifier ignored since `D' is the default (see `U')
#0 243.0   ar: `u' modifier ignored since `D' is the default (see `U')
#0 243.0   ../../build-aux/test-driver: line 107: 55096 Killed                  "$@" > $log_file 2>&1
#0 243.0   make[4]: *** [Makefile:1893: test-suite.log] Error 1
#0 243.0   make[3]: *** [Makefile:2001: check-TESTS] Error 2
#0 243.0   make[2]: *** [Makefile:2593: check-am] Error 2
#0 243.0   make[1]: *** [Makefile:401: check-recursive] Error 1
#0 243.0   make: *** [Makefile:514: check-recursive] Error 1
#0 243.0 
#0 243.0   ', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/exonum_libsodium-sys-0.0.23/build.rs:264:13
#0 243.0   stack backtrace:
#0 243.0      0: rust_begin_unwind
#0 243.0                at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
#0 243.0      1: core::panicking::panic_fmt
#0 243.0                at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
#0 243.0      2: build_script_build::main
#0 243.0                at ./build.rs:264:13
#0 243.0      3: core::ops::function::FnOnce::call_once
#0 243.0                at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5

**Comment by jsoneaday** [comment]
According to this link it appears that exonum_libsodium-sys is using an older version of libsodium? https://github.com/jedisct1/libsodium/discussions/1297
Is there any way to update the version of libsodium used?
